timeouts

diff --git a/startup.sh.template b/startup.sh.template
--- a/startup.sh.template
+++ b/startup.sh.template
@@ -3,18 +3,37 @@
 USER_LOG=/tmp/user-script.log
 function timedout() {
   TIMEOUT_LOG=/tmp/sivart/logs/timeout.log
-  ps auxw | grep sivart | grep -v '^root' | grep -v grep > $TIMEOUT_LOG
+  echo Timed out after SIVART_TIMEOUT seconds > $TIMEOUT_LOG
+  ps auxw | grep sivart | grep -v '^root' | grep -v grep >> $TIMEOUT_LOG
   nodejs /usr/local/sivart-slave/saveLogs.js $USER_LOG
   nodejs /usr/local/slivart-slave/deleteInstance.js
 }
 
 read -d '' SCRIPT <<'EOF'
-USER_SCRIPT
+SIVART_USER_SCRIPT
 EOF
 
+interval=5
 echo "$SCRIPT" > /tmp/user-script.sh
 
+(
+    ((t = SIVART_TIMEOUT))
+
+    while ((t > 0)); do
+        sleep $interval
+        kill -0 $$ || exit 0
+        ((t -= interval))
+    done
+
+    # Be nice, post SIGTERM first.
+    # The 'exit 0' below will be executed if any preceeding command fails.
+    timedout
+#    kill -s SIGTERM $$ && kill -0 $$ || exit 0
+#    sleep $delay
+#    kill -s SIGKILL $$
+) 2> /dev/null &
+
 echo '----------- START USER SCRIPT ---------------'
-#su -l sivart -c "/bin/bash /tmp/user-script" 2>&1 | tee /tmp/user-script.log
-( (sleep SIVART_TIMEOUT; timedout) & exec su -l sivart -c "/bin/bash /tmp/user-script.sh" 2>&1 | tee $USER_LOG )
+su -l sivart -c "/bin/bash /tmp/user-script.sh" 2>&1 | tee $USER_LOG
+#( (sleep SIVART_TIMEOUT; timedout) & exec su -l sivart -c "/bin/bash /tmp/user-script.sh" 2>&1 | tee $USER_LOG )
 echo '----------- END USER SCRIPT -----------------'
